#%RAML 1.0
title: ci-cd-test-api
version: v1

/test:
  post:
   body:
    application/json:
      example:
        {
          "nom": "konan"
        }
   responses:
    200:
      body:
        application/json:
          example:
            {
              "hasError": false
            }
            
            
/test2:
  post:
   body:
    application/json:
      example:
        {
          "nom": "konan"
        }
   responses:
    200:
      body:
        application/json:
          example:
            {
              "hasError": false,
              "description": "ok"
            }
        